# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 471)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuaction = QtWidgets.QMenu(self.menubar)
        self.menuaction.setObjectName("menuaction")
        self.menulayer = QtWidgets.QMenu(self.menubar)
        self.menulayer.setObjectName("menulayer")
        self.menuvector = QtWidgets.QMenu(self.menulayer)
        self.menuvector.setObjectName("menuvector")
        self.menuraster = QtWidgets.QMenu(self.menulayer)
        self.menuraster.setObjectName("menuraster")
        self.menumaptool = QtWidgets.QMenu(self.menubar)
        self.menumaptool.setObjectName("menumaptool")
        self.menuproject = QtWidgets.QMenu(self.menubar)
        self.menuproject.setObjectName("menuproject")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarProject = QtWidgets.QToolBar(MainWindow)
        self.toolBarProject.setObjectName("toolBarProject")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarProject)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.toolBarAction = QtWidgets.QToolBar(MainWindow)
        self.toolBarAction.setObjectName("toolBarAction")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarAction)
        self.toolBarLayer = QtWidgets.QToolBar(MainWindow)
        self.toolBarLayer.setObjectName("toolBarLayer")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarLayer)
        MainWindow.insertToolBarBreak(self.toolBarLayer)
        self.toolBarMapTool = QtWidgets.QToolBar(MainWindow)
        self.toolBarMapTool.setObjectName("toolBarMapTool")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarMapTool)
        self.toolBarProjection = QtWidgets.QToolBar(MainWindow)
        self.toolBarProjection.setObjectName("toolBarProjection")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarProjection)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionZoomin = QtWidgets.QAction(MainWindow)
        self.actionZoomin.setObjectName("actionZoomin")
        self.actionZoomout = QtWidgets.QAction(MainWindow)
        self.actionZoomout.setObjectName("actionZoomout")
        self.actionIdentity = QtWidgets.QAction(MainWindow)
        self.actionIdentity.setObjectName("actionIdentity")
        self.actionShapefile = QtWidgets.QAction(MainWindow)
        self.actionShapefile.setObjectName("actionShapefile")
        self.actionCsv = QtWidgets.QAction(MainWindow)
        self.actionCsv.setObjectName("actionCsv")
        self.actionPostGIS = QtWidgets.QAction(MainWindow)
        self.actionPostGIS.setObjectName("actionPostGIS")
        self.actionWFS = QtWidgets.QAction(MainWindow)
        self.actionWFS.setObjectName("actionWFS")
        self.actionGeotiff = QtWidgets.QAction(MainWindow)
        self.actionGeotiff.setObjectName("actionGeotiff")
        self.actionRectangle = QtWidgets.QAction(MainWindow)
        self.actionRectangle.setObjectName("actionRectangle")
        self.actionPolygon = QtWidgets.QAction(MainWindow)
        self.actionPolygon.setObjectName("actionPolygon")
        self.actionCircle = QtWidgets.QAction(MainWindow)
        self.actionCircle.setObjectName("actionCircle")
        self.actionPoint = QtWidgets.QAction(MainWindow)
        self.actionPoint.setObjectName("actionPoint")
        self.actionLine = QtWidgets.QAction(MainWindow)
        self.actionLine.setObjectName("actionLine")
        self.actionXYZ = QtWidgets.QAction(MainWindow)
        self.actionXYZ.setObjectName("actionXYZ")
        self.actionTransform = QtWidgets.QAction(MainWindow)
        self.actionTransform.setObjectName("actionTransform")
        self.actionPan = QtWidgets.QAction(MainWindow)
        self.actionPan.setObjectName("actionPan")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menufile.addAction(self.actionOpen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionQuit)
        self.menuaction.addAction(self.actionPan)
        self.menuaction.addAction(self.actionZoomin)
        self.menuaction.addAction(self.actionZoomout)
        self.menuaction.addAction(self.actionIdentity)
        self.menuvector.addAction(self.actionShapefile)
        self.menuvector.addAction(self.actionCsv)
        self.menuvector.addAction(self.actionPostGIS)
        self.menuvector.addAction(self.actionWFS)
        self.menuraster.addAction(self.actionGeotiff)
        self.menuraster.addAction(self.actionXYZ)
        self.menulayer.addAction(self.menuvector.menuAction())
        self.menulayer.addAction(self.menuraster.menuAction())
        self.menumaptool.addAction(self.actionPoint)
        self.menumaptool.addAction(self.actionLine)
        self.menumaptool.addAction(self.actionPolygon)
        self.menumaptool.addAction(self.actionRectangle)
        self.menumaptool.addAction(self.actionCircle)
        self.menuproject.addAction(self.actionTransform)
        self.menuhelp.addAction(self.actionAbout_Qt)
        self.menuhelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuaction.menuAction())
        self.menubar.addAction(self.menulayer.menuAction())
        self.menubar.addAction(self.menumaptool.menuAction())
        self.menubar.addAction(self.menuproject.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())
        self.toolBarProject.addAction(self.actionOpen)
        self.toolBarAction.addAction(self.actionPan)
        self.toolBarAction.addAction(self.actionZoomin)
        self.toolBarAction.addAction(self.actionZoomout)
        self.toolBarAction.addAction(self.actionIdentity)
        self.toolBarLayer.addAction(self.actionShapefile)
        self.toolBarLayer.addAction(self.actionCsv)
        self.toolBarLayer.addAction(self.actionPostGIS)
        self.toolBarLayer.addAction(self.actionWFS)
        self.toolBarLayer.addAction(self.actionGeotiff)
        self.toolBarLayer.addAction(self.actionXYZ)
        self.toolBarMapTool.addAction(self.actionPoint)
        self.toolBarMapTool.addAction(self.actionLine)
        self.toolBarMapTool.addAction(self.actionPolygon)
        self.toolBarMapTool.addAction(self.actionRectangle)
        self.toolBarMapTool.addAction(self.actionCircle)
        self.toolBarProjection.addAction(self.actionTransform)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menufile.setTitle(_translate("MainWindow", "Project"))
        self.menuaction.setTitle(_translate("MainWindow", "Action"))
        self.menulayer.setTitle(_translate("MainWindow", "Layer"))
        self.menuvector.setTitle(_translate("MainWindow", "Vector"))
        self.menuraster.setTitle(_translate("MainWindow", "Raster"))
        self.menumaptool.setTitle(_translate("MainWindow", "Maptool"))
        self.menuproject.setTitle(_translate("MainWindow", "Projection"))
        self.menuhelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBarProject.setWindowTitle(_translate("MainWindow", "toolBarProject"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "layer"))
        self.toolBarAction.setWindowTitle(_translate("MainWindow", "toolBarAction"))
        self.toolBarLayer.setWindowTitle(_translate("MainWindow", "toolBarLayer"))
        self.toolBarMapTool.setWindowTitle(_translate("MainWindow", "toolBarMapTool"))
        self.toolBarProjection.setWindowTitle(_translate("MainWindow", "toolBarProjection"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionZoomin.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoomout.setText(_translate("MainWindow", "Zoom out"))
        self.actionIdentity.setText(_translate("MainWindow", "Identify"))
        self.actionShapefile.setText(_translate("MainWindow", "Shapefile"))
        self.actionCsv.setText(_translate("MainWindow", "CSV"))
        self.actionPostGIS.setText(_translate("MainWindow", "PostGIS"))
        self.actionWFS.setText(_translate("MainWindow", "WFS"))
        self.actionGeotiff.setText(_translate("MainWindow", "Geotiff"))
        self.actionRectangle.setText(_translate("MainWindow", "Rectangle"))
        self.actionPolygon.setText(_translate("MainWindow", "Polygon"))
        self.actionCircle.setText(_translate("MainWindow", "Circle"))
        self.actionPoint.setText(_translate("MainWindow", "Point"))
        self.actionLine.setText(_translate("MainWindow", "Line"))
        self.actionXYZ.setText(_translate("MainWindow", "XYZ"))
        self.actionTransform.setText(_translate("MainWindow", "Transform"))
        self.actionPan.setText(_translate("MainWindow", "Pan"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

